package code

var (
	VariantNameRepeat                            = productError(1, "变体名称重复")
	VariantCountMax                              = productError(2, "变体数量超过限制")
	ProductConditionMust                         = productError(3, "自动匹配模式下必须设置条件")
	OnceMaxFind500                               = productError(4, "最多只能查询500个商品")
	InValidKey                                   = productError(5, "无效的键")
	InValidAction                                = productError(6, "无效的条件")
	NoEmptyVariants                              = productError(7, "至少需要一个变体")
	ProductCollectionTypeNotAllow                = productError(8, "不允许修改创建成功的商品系列类型")
	PurchaseItemIsEmpty                          = productError(9, "采购单商品不能为空")
	CarrierIdIsEmpty                             = productError(10, "请选择物流商")
	AdjustCountMax                               = productError(11, "最多只能添加8个调整项")
	ErrSupplierNotFound                          = productError(12, "供应商不存在或已被删除")
	PurchaseIsOrdered                            = productError(13, "采购单已标记为订购状态")
	PurchaseCanNotRemove                         = productError(14, "该采购单非草稿单，无法删除")
	DestinationIdNotUpdate                       = productError(15, "目的地ID不允许修改")
	SupplierIdNotUpdate                          = productError(16, "供应商ID不允许修改")
	SupplierAdjustError                          = productError(17, "采购单当前状态无法接收库存")
	PurchaseItemCanNotRemoveByReceivedOrRejected = productError(18, "无法删除已经接收/拒绝的商品")
	PurchaseStatusMissing                        = productError(19, "采购单状态为空")
	TransferStatusNoMark                         = productError(20, "当前状态无法标记为待收货")
	TransferStatusNotAdjust                      = productError(21, "当前状态无法收货")
	TransferStatusMissing                        = productError(22, "转单状态为空")
	ErrTransferStatusNotDrafts                   = productError(23, "该状态下无法删除转移")
	ProductNotTrackInventory                     = productError(24, "该商品不跟踪库存")
	PartProductNoFound                           = productError(25, "部分商品不存在或已被删除")
	ErrCollectionNotFound                        = productError(26, "商品系列不存在或已被删除")
)
